sudo: false
dist: trusty
language: node_js
node_js:
- '8'
addons:
  apt:
    packages:
    - python3-pip
script:
- npm test
- npm run cover
- npm run lint
after_sucess:
- ci/coveralls.sh
git:
  depth: 1
  submodules: false
cache:
  directories:
  - node_modules